parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ferror\SingleTablePattern\Presenter\Console\:
        resource: '../../src/SingleTablePattern/Presenter/Console/*'
