services:
    traefik:
        image: traefik:2.3
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            ferror:
                ipv4_address: 192.168.10.2

    dynamodb:
        image: amazon/dynamodb-local:1.15.0
        command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
        ports:
            - "8000:8000"
        depends_on:
            - traefik
        networks:
            - ferror

    dynamodb-admin:
        image: aaronshaf/dynamodb-admin
        ports:
            - "8001:8001"
        environment:
            DYNAMO_ENDPOINT: "http://dynamodb:8000"
        depends_on:
            - traefik
        networks:
            - ferror

    single-table:
        image: ferror/symfony-image:8.0
        command: ["make", "run"]
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.symfony.rule=Host(`symfony.malcherczyk.localhost`)"
        volumes:
            - ./:/app:delegated
        depends_on:
            - traefik
        networks:
            - ferror

networks:
    ferror:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.10.0/24
