imports:
    - 'services/aws.yaml'
    - 'services/console.yaml'

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ferror\SingleTablePattern\Infrastructure\Aws\Dynamodb\UserRepository:
        class: Ferror\SingleTablePattern\Infrastructure\Aws\Dynamodb\UserRepository
        arguments:
            - '@Ferror\SingleTablePattern\Infrastructure\Aws\Dynamodb\DynamoDatabase'


    Ferror\SingleTablePattern\Domain\UserRepository: '@Ferror\SingleTablePattern\Infrastructure\Aws\Dynamodb\UserRepository'

